version: "3.9"

services:
  cvzn-api:
    build: .
    container_name: cvzn-api
    ports:
      - "3000:3000"
    depends_on:
      - cvzn-db
    environment:
      - DATABASE_URL=postgresql://cvzn_user:cvzn_password@cvzn-db:5432/cvzn_db
    restart: unless-stopped
    networks:
      - my-custom-network

  cvzn-db:
    image: postgres:15-alpine
    container_name: cvzn-db
    environment:
      POSTGRES_USER: cvzn_user
      POSTGRES_PASSWORD: cvzn_password
      POSTGRES_DB: cvzn_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - my-custom-network

networks:
  my-custom-network:
    name: cvzn-network
    driver: bridge

volumes:
  db_data:
