version: "3.9"

services:
  pos-api:
    build: .
    container_name: pos-api
    ports:
      - "3000:3000"
    depends_on:
      - pos-db
    environment:
      - DATABASE_URL=postgresql://pos_user:pos_password@pos-db:5432/pos_db
    restart: unless-stopped
    networks:
      - my-custom-network

  pos-db:
    image: postgres:15-alpine
    container_name: pos-db
    environment:
      POSTGRES_USER: pos_user
      POSTGRES_PASSWORD: pos_password
      POSTGRES_DB: pos_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - my-custom-network

networks:
  my-custom-network:
    name: pos-network
    driver: bridge

volumes:
  db_data:
